# Generated by Django 5.2.6 on 2025-09-27 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Usuarios', '0002_alter_usuario_tc_alter_usuario_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ven', models.DateField()),
                ('fecha_com', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_com', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.almacen')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Administra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.empleado')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.almacen')),
            ],
            options={
                'unique_together': {('empleado', 'almacen')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.retiro')),
            ],
            options={
                'unique_together': {('producto', 'retiro')},
            },
        ),
    ]
