# Generated by Django 5.2.5 on 2025-11-05 04:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Productos', '0002_producto_imagen'),
        ('Usuarios', '0005_alter_bitacora_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='fecha_ven',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='precio_com',
        ),
        migrations.RemoveField(
            model_name='suministro',
            name='producto',
        ),
        migrations.AddField(
            model_name='retiro',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='retiro',
            name='tipo',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('MAN', 'Manual')], default='MAN', max_length=5),
        ),
        migrations.AddField(
            model_name='suministro',
            name='nro_suministro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='suministro',
            name='total_com',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleretiro',
            name='retiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.retiro'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='fecha_com',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DetalleSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_com', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ven', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.suministro')),
            ],
        ),
    ]
