# Generated by Django 5.2.5 on 2025-11-05 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Usuarios', '0005_alter_bitacora_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='retiro',
            name='tipo',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('MAN', 'Manual')], default='MAN', max_length=5),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
