# Generated by Django 5.2.5 on 2025-11-05 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_retiro_empleado_retiro_tipo_alter_retiro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleretiro',
            name='retiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.retiro'),
        ),
    ]
