# Generated by Django 5.2.5 on 2025-11-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_notificacion_reserva_detallereserva_venta_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
