# Generated by Django 5.2.5 on 2025-11-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_bitacora_descripcion'),
        ('Ventas', '0003_reserva_detallereserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Usuarios.empleado')),
            ],
        ),
    ]
