# Generated by Django 5.2.5 on 2025-11-25 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_venta_entregado_venta_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
