# Generated by Django 5.2.5 on 2025-11-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='Ventas.reserva'),
        ),
    ]
