# Generated by Django 5.2.5 on 2025-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
