# Generated by Django 5.2.5 on 2025-11-26 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
