# Generated by Django 5.2.6 on 2025-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_tc_alter_usuario_te'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ci',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
