# Generated by Django 5.2.5 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_empleado_sueldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
